# Generated by Django 4.2.23 on 2025-08-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin Team')], default='user', max_length=16, verbose_name='Роль'),
        ),
    ]
