# Generated by Django 4.2.23 on 2025-08-15 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название команды', max_length=256, verbose_name='Название команды')),
                ('team', models.ManyToManyField(help_text='Выберите участников для команды', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды')),
            ],
        ),
    ]
