# Generated by Django 4.2.23 on 2025-08-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название Задачи', max_length=256, verbose_name='Название Задачи')),
                ('description', models.TextField(help_text='Введите описание задачи', verbose_name='Описание задачи')),
                ('deadline', models.DateField(help_text='Укажите дедлайн задачи', verbose_name='Дедлайн задачи')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('progress', 'В работе'), ('completed', 'Выполнена')], default='open', max_length=20, verbose_name='Статус задачи')),
                ('team', models.ForeignKey(help_text='Укажите команду', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teamflow.team', verbose_name='Команда')),
            ],
        ),
    ]
