# Generated by Django 4.2.23 on 2025-08-26 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(help_text='Выберите участников для команды', related_name='teams', through='teamflow.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(help_text='Укажите автора', on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(help_text='Укажите исполнителя', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(help_text='Укажите команду', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teamflow.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teamflow.team'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(help_text='Пользователь создавший встречу', on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Организатор встречи '),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(help_text='Выберите участников для встречи', related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Участники встречи'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(help_text='Укажите кто оценил задачу', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Автор оценки'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='task',
            field=models.ForeignKey(help_text='Укажите задачу', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='teamflow.task', verbose_name='задача'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(help_text='Комментарий задачи', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teamflow.task', verbose_name='Задача'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('task', 'evaluator')},
        ),
    ]
