# Generated by Django 4.2.23 on 2025-08-15 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamflow', '0003_alter_task_options_alter_team_options_task_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=1, help_text='Укажите автора', on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(default=1, help_text='Укажите исполнителя', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(help_text='Укажите команду', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teamflow.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.ManyToManyField(help_text='Выберите участников для команды', related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
    ]
