# Generated by Django 4.2.23 on 2025-08-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0003_alter_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='team',
            field=models.ForeignKey(default=1, help_text='Команда у которой встречи', on_delete=django.db.models.deletion.CASCADE, related_name='team_meetings', to='teamflow.team', verbose_name='Команда'),
            preserve_default=False,
        ),
    ]
