# Generated by Django 4.2.23 on 2025-08-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamflow', '0004_meeting_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='organizer',
        ),
        migrations.AddField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(default=1, help_text='Пользователь создавший встречу', on_delete=django.db.models.deletion.CASCADE, related_name='author_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Организатор встречи '),
            preserve_default=False,
        ),
    ]
