# Generated by Django 4.2.23 on 2025-08-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0004_remove_task_user_task_author_task_executor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='participants',
        ),
    ]
