# Generated by Django 4.2.23 on 2025-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0005_remove_meeting_organizer_meeting_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(help_text='Введите название команды', max_length=256, unique=True, verbose_name='Название команды'),
        ),
    ]
