# Generated by Django 4.2.23 on 2025-08-16 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamflow', '0009_alter_evaluation_unique_together_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(default=1, help_text='Пользователь создавший встречу', on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Организатор встречи '),
            preserve_default=False,
        ),
    ]
